import typing_extensions

from mastercard_python_sdk.paths import PathValues
from mastercard_python_sdk.apis.paths.aggregation_v2_partners_authentication import AggregationV2PartnersAuthentication
from mastercard_python_sdk.apis.paths.connect_v2_generate import ConnectV2Generate
from mastercard_python_sdk.apis.paths.connect_v2_generate_lite import ConnectV2GenerateLite
from mastercard_python_sdk.apis.paths.connect_v2_generate_fix import ConnectV2GenerateFix
from mastercard_python_sdk.apis.paths.connect_v2_send_email import ConnectV2SendEmail
from mastercard_python_sdk.apis.paths.connect_v2_generate_joint_borrower import ConnectV2GenerateJointBorrower
from mastercard_python_sdk.apis.paths.connect_v2_generate_microentry_verify import ConnectV2GenerateMicroentryVerify
from mastercard_python_sdk.apis.paths.connect_v2_send_email_joint_borrower import ConnectV2SendEmailJointBorrower
from mastercard_python_sdk.apis.paths.aggregation_v2_customers_testing import AggregationV2CustomersTesting
from mastercard_python_sdk.apis.paths.aggregation_v2_customers_active import AggregationV2CustomersActive
from mastercard_python_sdk.apis.paths.aggregation_v1_customers import AggregationV1Customers
from mastercard_python_sdk.apis.paths.aggregation_v1_customers_customer_id_application import AggregationV1CustomersCustomerIdApplication
from mastercard_python_sdk.apis.paths.aggregation_v1_customers_customer_id import AggregationV1CustomersCustomerId
from mastercard_python_sdk.apis.paths.decisioning_v1_customers_customer_id_consumer import DecisioningV1CustomersCustomerIdConsumer
from mastercard_python_sdk.apis.paths.decisioning_v1_consumers_consumer_id import DecisioningV1ConsumersConsumerId
from mastercard_python_sdk.apis.paths.aggregation_v1_customers_customer_id_institution_logins_institution_login_id_accounts import AggregationV1CustomersCustomerIdInstitutionLoginsInstitutionLoginIdAccounts
from mastercard_python_sdk.apis.paths.aggregation_v2_customers_customer_id_institution_logins_institution_login_id_accounts import AggregationV2CustomersCustomerIdInstitutionLoginsInstitutionLoginIdAccounts
from mastercard_python_sdk.apis.paths.aggregation_v1_customers_customer_id_institution_logins_institution_login_id import AggregationV1CustomersCustomerIdInstitutionLoginsInstitutionLoginId
from mastercard_python_sdk.apis.paths.aggregation_v2_customers_customer_id_accounts_account_id import AggregationV2CustomersCustomerIdAccountsAccountId
from mastercard_python_sdk.apis.paths.aggregation_v1_customers_customer_id_accounts_account_id import AggregationV1CustomersCustomerIdAccountsAccountId
from mastercard_python_sdk.apis.paths.aggregation_v1_customers_customer_id_accounts import AggregationV1CustomersCustomerIdAccounts
from mastercard_python_sdk.apis.paths.aggregation_v2_customers_customer_id_accounts import AggregationV2CustomersCustomerIdAccounts
from mastercard_python_sdk.apis.paths.aggregation_v1_customers_customer_id_institutions_institution_id_accounts import AggregationV1CustomersCustomerIdInstitutionsInstitutionIdAccounts
from mastercard_python_sdk.apis.paths.aggregation_v1_customers_customer_id_institutions_institution_id_accounts_simple import AggregationV1CustomersCustomerIdInstitutionsInstitutionIdAccountsSimple
from mastercard_python_sdk.apis.paths.aggregation_v1_customers_customer_id_institution_logins_institution_login_id_accounts_simple import AggregationV1CustomersCustomerIdInstitutionLoginsInstitutionLoginIdAccountsSimple
from mastercard_python_sdk.apis.paths.aggregation_v1_customers_customer_id_accounts_account_id_simple import AggregationV1CustomersCustomerIdAccountsAccountIdSimple
from mastercard_python_sdk.apis.paths.aggregation_v1_customers_customer_id_accounts_simple import AggregationV1CustomersCustomerIdAccountsSimple
from mastercard_python_sdk.apis.paths.aggregation_v1_customers_customer_id_accounts_account_id_transactions_historic import AggregationV1CustomersCustomerIdAccountsAccountIdTransactionsHistoric
from mastercard_python_sdk.apis.paths.aggregation_v1_customers_customer_id_accounts_account_id_owner import AggregationV1CustomersCustomerIdAccountsAccountIdOwner
from mastercard_python_sdk.apis.paths.aggregation_v3_customers_customer_id_accounts_account_id_owner import AggregationV3CustomersCustomerIdAccountsAccountIdOwner
from mastercard_python_sdk.apis.paths.aggregation_v1_partners_applications import AggregationV1PartnersApplications
from mastercard_python_sdk.apis.paths.aggregation_v1_partners_applications_pre_app_id import AggregationV1PartnersApplicationsPreAppId
from mastercard_python_sdk.apis.paths.aggregation_v2_partners_applications import AggregationV2PartnersApplications
from mastercard_python_sdk.apis.paths.aggregation_v1_customers_customer_id_applications_application_id import AggregationV1CustomersCustomerIdApplicationsApplicationId
from mastercard_python_sdk.apis.paths.aggregation_v2_customers_customer_id_institution_logins_institution_login_id_migration import AggregationV2CustomersCustomerIdInstitutionLoginsInstitutionLoginIdMigration
from mastercard_python_sdk.apis.paths.institution_v2_certified_institutions_rssd import InstitutionV2CertifiedInstitutionsRssd
from mastercard_python_sdk.apis.paths.institution_v2_institutions import InstitutionV2Institutions
from mastercard_python_sdk.apis.paths.institution_v2_certified_institutions import InstitutionV2CertifiedInstitutions
from mastercard_python_sdk.apis.paths.institution_v2_institutions_institution_id import InstitutionV2InstitutionsInstitutionId
from mastercard_python_sdk.apis.paths.institution_v2_institutions_institution_id_branding import InstitutionV2InstitutionsInstitutionIdBranding
from mastercard_python_sdk.apis.paths.decisioning_v2_customers_customer_id_voa import DecisioningV2CustomersCustomerIdVoa
from mastercard_python_sdk.apis.paths.decisioning_v2_customers_customer_id_voa_history import DecisioningV2CustomersCustomerIdVoaHistory
from mastercard_python_sdk.apis.paths.decisioning_v2_customers_customer_id_pre_qual_voa import DecisioningV2CustomersCustomerIdPreQualVoa
from mastercard_python_sdk.apis.paths.decisioning_v2_customers_customer_id_asset_summary import DecisioningV2CustomersCustomerIdAssetSummary
from mastercard_python_sdk.apis.paths.decisioning_v2_customers_customer_id_voi import DecisioningV2CustomersCustomerIdVoi
from mastercard_python_sdk.apis.paths.decisioning_v2_customers_customer_id_voe_payroll import DecisioningV2CustomersCustomerIdVoePayroll
from mastercard_python_sdk.apis.paths.decisioning_v2_customers_customer_id_voe_transactions import DecisioningV2CustomersCustomerIdVoeTransactions
from mastercard_python_sdk.apis.paths.decisioning_v2_customers_customer_id_pay_statement import DecisioningV2CustomersCustomerIdPayStatement
from mastercard_python_sdk.apis.paths.decisioning_v2_customers_customer_id_voie_tx_verify_with_interview import DecisioningV2CustomersCustomerIdVoieTxVerifyWithInterview
from mastercard_python_sdk.apis.paths.decisioning_v2_customers_customer_id_voie_tx_verify_with_statement import DecisioningV2CustomersCustomerIdVoieTxVerifyWithStatement
from mastercard_python_sdk.apis.paths.decisioning_v2_customers_customer_id_voie_payroll import DecisioningV2CustomersCustomerIdVoiePayroll
from mastercard_python_sdk.apis.paths.aggregation_v1_customers_customer_id_accounts_account_id_statement import AggregationV1CustomersCustomerIdAccountsAccountIdStatement
from mastercard_python_sdk.apis.paths.decisioning_v2_customers_customer_id_statement import DecisioningV2CustomersCustomerIdStatement
from mastercard_python_sdk.apis.paths.aggregation_v3_customers_customer_id_accounts_account_id_statement import AggregationV3CustomersCustomerIdAccountsAccountIdStatement
from mastercard_python_sdk.apis.paths.aggregation_v3_customers_customer_id_transactions import AggregationV3CustomersCustomerIdTransactions
from mastercard_python_sdk.apis.paths.aggregation_v2_customers_customer_id_transactions_transaction_id import AggregationV2CustomersCustomerIdTransactionsTransactionId
from mastercard_python_sdk.apis.paths.aggregation_v4_customers_customer_id_accounts_account_id_transactions import AggregationV4CustomersCustomerIdAccountsAccountIdTransactions
from mastercard_python_sdk.apis.paths.decisioning_v2_customers_customer_id_transactions import DecisioningV2CustomersCustomerIdTransactions
from mastercard_python_sdk.apis.paths.decisioning_v2_customers_customer_id_reports_balance_analytics_user_types_user_type import DecisioningV2CustomersCustomerIdReportsBalanceAnalyticsUserTypesUserType
from mastercard_python_sdk.apis.paths.decisioning_v2_customers_customer_id_reports_cashflow_analytics_user_types_user_type import DecisioningV2CustomersCustomerIdReportsCashflowAnalyticsUserTypesUserType
from mastercard_python_sdk.apis.paths.aggregation_v1_customers_customer_id_pay_statements import AggregationV1CustomersCustomerIdPayStatements
from mastercard_python_sdk.apis.paths.aggregation_v2_customers_customer_id_accounts_account_id_loan_details import AggregationV2CustomersCustomerIdAccountsAccountIdLoanDetails
from mastercard_python_sdk.apis.paths.decisioning_v1_customers_customer_id_portfolios_portfolio_id import DecisioningV1CustomersCustomerIdPortfoliosPortfolioId
from mastercard_python_sdk.apis.paths.aggregation_v1_customers_customer_id_accounts_account_id_txpush import AggregationV1CustomersCustomerIdAccountsAccountIdTxpush
from mastercard_python_sdk.apis.paths.aggregation_v1_customers_customer_id_accounts_account_id_transactions import AggregationV1CustomersCustomerIdAccountsAccountIdTransactions
from mastercard_python_sdk.apis.paths.aggregation_v1_customers_customer_id_subscriptions_subscription_id import AggregationV1CustomersCustomerIdSubscriptionsSubscriptionId
from mastercard_python_sdk.apis.paths.decisioning_v1_consumers_consumer_id_portfolios_portfolio_id import DecisioningV1ConsumersConsumerIdPortfoliosPortfolioId
from mastercard_python_sdk.apis.paths.aggregation_v1_customers_customer_id_accounts_account_id_details import AggregationV1CustomersCustomerIdAccountsAccountIdDetails
from mastercard_python_sdk.apis.paths.decisioning_v3_customers_customer_id_reports_report_id import DecisioningV3CustomersCustomerIdReportsReportId
from mastercard_python_sdk.apis.paths.decisioning_v3_consumers_consumer_id_reports_report_id import DecisioningV3ConsumersConsumerIdReportsReportId
from mastercard_python_sdk.apis.paths.decisioning_v1_customers_customer_id_reports import DecisioningV1CustomersCustomerIdReports
from mastercard_python_sdk.apis.paths.decisioning_v1_consumers_consumer_id_reports import DecisioningV1ConsumersConsumerIdReports
from mastercard_python_sdk.apis.paths.aggregation_v1_customers_customer_id_assets_asset_id import AggregationV1CustomersCustomerIdAssetsAssetId
from mastercard_python_sdk.apis.paths.aggregation_v1_customers_customer_id_accounts_account_id_available_balance_live import AggregationV1CustomersCustomerIdAccountsAccountIdAvailableBalanceLive
from mastercard_python_sdk.apis.paths.aggregation_v1_customers_customer_id_accounts_account_id_available_balance import AggregationV1CustomersCustomerIdAccountsAccountIdAvailableBalance
from mastercard_python_sdk.apis.paths.decisioning_v2_customers_customer_id_cash_flow_business import DecisioningV2CustomersCustomerIdCashFlowBusiness
from mastercard_python_sdk.apis.paths.decisioning_v2_customers_customer_id_cash_flow_personal import DecisioningV2CustomersCustomerIdCashFlowPersonal
from mastercard_python_sdk.apis.paths.microentry_v1_customers_customer_id import MicroentryV1CustomersCustomerId
from mastercard_python_sdk.apis.paths.microentry_v1_customers_customer_id_accounts_account_id_amounts import MicroentryV1CustomersCustomerIdAccountsAccountIdAmounts
from mastercard_python_sdk.apis.paths.microentry_v1_customers_customer_id_accounts_account_id import MicroentryV1CustomersCustomerIdAccountsAccountId
from mastercard_python_sdk.apis.paths.analytics_balance_v1_customer_customer_id import AnalyticsBalanceV1CustomerCustomerId
from mastercard_python_sdk.apis.paths.analytics_balance_v1_customer_customer_id_fcra import AnalyticsBalanceV1CustomerCustomerIdFcra
from mastercard_python_sdk.apis.paths.analytics_cashflow_v1_customer_customer_id import AnalyticsCashflowV1CustomerCustomerId
from mastercard_python_sdk.apis.paths.analytics_cashflow_v1_customer_customer_id_fcra import AnalyticsCashflowV1CustomerCustomerIdFcra
from mastercard_python_sdk.apis.paths.analytics_payment_history_v1_customer_customer_id import AnalyticsPaymentHistoryV1CustomerCustomerId
from mastercard_python_sdk.apis.paths.analytics_payment_history_v1_customer_customer_id_fcra import AnalyticsPaymentHistoryV1CustomerCustomerIdFcra
from mastercard_python_sdk.apis.paths.analytics_data_v1_obb_report_id import AnalyticsDataV1ObbReportId
from mastercard_python_sdk.apis.paths.analytics_data_v1_obb_report_id_fcra import AnalyticsDataV1ObbReportIdFcra
from mastercard_python_sdk.apis.paths.aggregation_v1_partners_access_key import AggregationV1PartnersAccessKey
from mastercard_python_sdk.apis.paths.aggregation_v1_partners_access_key_consent_receipt_id import AggregationV1PartnersAccessKeyConsentReceiptId
from mastercard_python_sdk.apis.paths.customers_institution_logins_institution_login_id_authorization_details import CustomersInstitutionLoginsInstitutionLoginIdAuthorizationDetails
from mastercard_python_sdk.apis.paths.business_services_customers_customer_id_businesses import BusinessServicesCustomersCustomerIdBusinesses
from mastercard_python_sdk.apis.paths.business_services_businesses_business_id import BusinessServicesBusinessesBusinessId

PathToApi = typing_extensions.TypedDict(
    'PathToApi',
    {
        PathValues.AGGREGATION_V2_PARTNERS_AUTHENTICATION: AggregationV2PartnersAuthentication,
        PathValues.CONNECT_V2_GENERATE: ConnectV2Generate,
        PathValues.CONNECT_V2_GENERATE_LITE: ConnectV2GenerateLite,
        PathValues.CONNECT_V2_GENERATE_FIX: ConnectV2GenerateFix,
        PathValues.CONNECT_V2_SEND_EMAIL: ConnectV2SendEmail,
        PathValues.CONNECT_V2_GENERATE_JOINT_BORROWER: ConnectV2GenerateJointBorrower,
        PathValues.CONNECT_V2_GENERATE_MICROENTRY_VERIFY: ConnectV2GenerateMicroentryVerify,
        PathValues.CONNECT_V2_SEND_EMAIL_JOINT_BORROWER: ConnectV2SendEmailJointBorrower,
        PathValues.AGGREGATION_V2_CUSTOMERS_TESTING: AggregationV2CustomersTesting,
        PathValues.AGGREGATION_V2_CUSTOMERS_ACTIVE: AggregationV2CustomersActive,
        PathValues.AGGREGATION_V1_CUSTOMERS: AggregationV1Customers,
        PathValues.AGGREGATION_V1_CUSTOMERS_CUSTOMER_ID_APPLICATION: AggregationV1CustomersCustomerIdApplication,
        PathValues.AGGREGATION_V1_CUSTOMERS_CUSTOMER_ID: AggregationV1CustomersCustomerId,
        PathValues.DECISIONING_V1_CUSTOMERS_CUSTOMER_ID_CONSUMER: DecisioningV1CustomersCustomerIdConsumer,
        PathValues.DECISIONING_V1_CONSUMERS_CONSUMER_ID: DecisioningV1ConsumersConsumerId,
        PathValues.AGGREGATION_V1_CUSTOMERS_CUSTOMER_ID_INSTITUTION_LOGINS_INSTITUTION_LOGIN_ID_ACCOUNTS: AggregationV1CustomersCustomerIdInstitutionLoginsInstitutionLoginIdAccounts,
        PathValues.AGGREGATION_V2_CUSTOMERS_CUSTOMER_ID_INSTITUTION_LOGINS_INSTITUTION_LOGIN_ID_ACCOUNTS: AggregationV2CustomersCustomerIdInstitutionLoginsInstitutionLoginIdAccounts,
        PathValues.AGGREGATION_V1_CUSTOMERS_CUSTOMER_ID_INSTITUTION_LOGINS_INSTITUTION_LOGIN_ID: AggregationV1CustomersCustomerIdInstitutionLoginsInstitutionLoginId,
        PathValues.AGGREGATION_V2_CUSTOMERS_CUSTOMER_ID_ACCOUNTS_ACCOUNT_ID: AggregationV2CustomersCustomerIdAccountsAccountId,
        PathValues.AGGREGATION_V1_CUSTOMERS_CUSTOMER_ID_ACCOUNTS_ACCOUNT_ID: AggregationV1CustomersCustomerIdAccountsAccountId,
        PathValues.AGGREGATION_V1_CUSTOMERS_CUSTOMER_ID_ACCOUNTS: AggregationV1CustomersCustomerIdAccounts,
        PathValues.AGGREGATION_V2_CUSTOMERS_CUSTOMER_ID_ACCOUNTS: AggregationV2CustomersCustomerIdAccounts,
        PathValues.AGGREGATION_V1_CUSTOMERS_CUSTOMER_ID_INSTITUTIONS_INSTITUTION_ID_ACCOUNTS: AggregationV1CustomersCustomerIdInstitutionsInstitutionIdAccounts,
        PathValues.AGGREGATION_V1_CUSTOMERS_CUSTOMER_ID_INSTITUTIONS_INSTITUTION_ID_ACCOUNTS_SIMPLE: AggregationV1CustomersCustomerIdInstitutionsInstitutionIdAccountsSimple,
        PathValues.AGGREGATION_V1_CUSTOMERS_CUSTOMER_ID_INSTITUTION_LOGINS_INSTITUTION_LOGIN_ID_ACCOUNTS_SIMPLE: AggregationV1CustomersCustomerIdInstitutionLoginsInstitutionLoginIdAccountsSimple,
        PathValues.AGGREGATION_V1_CUSTOMERS_CUSTOMER_ID_ACCOUNTS_ACCOUNT_ID_SIMPLE: AggregationV1CustomersCustomerIdAccountsAccountIdSimple,
        PathValues.AGGREGATION_V1_CUSTOMERS_CUSTOMER_ID_ACCOUNTS_SIMPLE: AggregationV1CustomersCustomerIdAccountsSimple,
        PathValues.AGGREGATION_V1_CUSTOMERS_CUSTOMER_ID_ACCOUNTS_ACCOUNT_ID_TRANSACTIONS_HISTORIC: AggregationV1CustomersCustomerIdAccountsAccountIdTransactionsHistoric,
        PathValues.AGGREGATION_V1_CUSTOMERS_CUSTOMER_ID_ACCOUNTS_ACCOUNT_ID_OWNER: AggregationV1CustomersCustomerIdAccountsAccountIdOwner,
        PathValues.AGGREGATION_V3_CUSTOMERS_CUSTOMER_ID_ACCOUNTS_ACCOUNT_ID_OWNER: AggregationV3CustomersCustomerIdAccountsAccountIdOwner,
        PathValues.AGGREGATION_V1_PARTNERS_APPLICATIONS: AggregationV1PartnersApplications,
        PathValues.AGGREGATION_V1_PARTNERS_APPLICATIONS_PRE_APP_ID: AggregationV1PartnersApplicationsPreAppId,
        PathValues.AGGREGATION_V2_PARTNERS_APPLICATIONS: AggregationV2PartnersApplications,
        PathValues.AGGREGATION_V1_CUSTOMERS_CUSTOMER_ID_APPLICATIONS_APPLICATION_ID: AggregationV1CustomersCustomerIdApplicationsApplicationId,
        PathValues.AGGREGATION_V2_CUSTOMERS_CUSTOMER_ID_INSTITUTION_LOGINS_INSTITUTION_LOGIN_ID_MIGRATION: AggregationV2CustomersCustomerIdInstitutionLoginsInstitutionLoginIdMigration,
        PathValues.INSTITUTION_V2_CERTIFIED_INSTITUTIONS_RSSD: InstitutionV2CertifiedInstitutionsRssd,
        PathValues.INSTITUTION_V2_INSTITUTIONS: InstitutionV2Institutions,
        PathValues.INSTITUTION_V2_CERTIFIED_INSTITUTIONS: InstitutionV2CertifiedInstitutions,
        PathValues.INSTITUTION_V2_INSTITUTIONS_INSTITUTION_ID: InstitutionV2InstitutionsInstitutionId,
        PathValues.INSTITUTION_V2_INSTITUTIONS_INSTITUTION_ID_BRANDING: InstitutionV2InstitutionsInstitutionIdBranding,
        PathValues.DECISIONING_V2_CUSTOMERS_CUSTOMER_ID_VOA: DecisioningV2CustomersCustomerIdVoa,
        PathValues.DECISIONING_V2_CUSTOMERS_CUSTOMER_ID_VOA_HISTORY: DecisioningV2CustomersCustomerIdVoaHistory,
        PathValues.DECISIONING_V2_CUSTOMERS_CUSTOMER_ID_PRE_QUAL_VOA: DecisioningV2CustomersCustomerIdPreQualVoa,
        PathValues.DECISIONING_V2_CUSTOMERS_CUSTOMER_ID_ASSET_SUMMARY: DecisioningV2CustomersCustomerIdAssetSummary,
        PathValues.DECISIONING_V2_CUSTOMERS_CUSTOMER_ID_VOI: DecisioningV2CustomersCustomerIdVoi,
        PathValues.DECISIONING_V2_CUSTOMERS_CUSTOMER_ID_VOE_PAYROLL: DecisioningV2CustomersCustomerIdVoePayroll,
        PathValues.DECISIONING_V2_CUSTOMERS_CUSTOMER_ID_VOE_TRANSACTIONS: DecisioningV2CustomersCustomerIdVoeTransactions,
        PathValues.DECISIONING_V2_CUSTOMERS_CUSTOMER_ID_PAY_STATEMENT: DecisioningV2CustomersCustomerIdPayStatement,
        PathValues.DECISIONING_V2_CUSTOMERS_CUSTOMER_ID_VOIE_TX_VERIFY_WITH_INTERVIEW: DecisioningV2CustomersCustomerIdVoieTxVerifyWithInterview,
        PathValues.DECISIONING_V2_CUSTOMERS_CUSTOMER_ID_VOIE_TX_VERIFY_WITH_STATEMENT: DecisioningV2CustomersCustomerIdVoieTxVerifyWithStatement,
        PathValues.DECISIONING_V2_CUSTOMERS_CUSTOMER_ID_VOIE_PAYROLL: DecisioningV2CustomersCustomerIdVoiePayroll,
        PathValues.AGGREGATION_V1_CUSTOMERS_CUSTOMER_ID_ACCOUNTS_ACCOUNT_ID_STATEMENT: AggregationV1CustomersCustomerIdAccountsAccountIdStatement,
        PathValues.DECISIONING_V2_CUSTOMERS_CUSTOMER_ID_STATEMENT: DecisioningV2CustomersCustomerIdStatement,
        PathValues.AGGREGATION_V3_CUSTOMERS_CUSTOMER_ID_ACCOUNTS_ACCOUNT_ID_STATEMENT: AggregationV3CustomersCustomerIdAccountsAccountIdStatement,
        PathValues.AGGREGATION_V3_CUSTOMERS_CUSTOMER_ID_TRANSACTIONS: AggregationV3CustomersCustomerIdTransactions,
        PathValues.AGGREGATION_V2_CUSTOMERS_CUSTOMER_ID_TRANSACTIONS_TRANSACTION_ID: AggregationV2CustomersCustomerIdTransactionsTransactionId,
        PathValues.AGGREGATION_V4_CUSTOMERS_CUSTOMER_ID_ACCOUNTS_ACCOUNT_ID_TRANSACTIONS: AggregationV4CustomersCustomerIdAccountsAccountIdTransactions,
        PathValues.DECISIONING_V2_CUSTOMERS_CUSTOMER_ID_TRANSACTIONS: DecisioningV2CustomersCustomerIdTransactions,
        PathValues.DECISIONING_V2_CUSTOMERS_CUSTOMER_ID_REPORTS_BALANCEANALYTICS_USER_TYPES_USER_TYPE: DecisioningV2CustomersCustomerIdReportsBalanceAnalyticsUserTypesUserType,
        PathValues.DECISIONING_V2_CUSTOMERS_CUSTOMER_ID_REPORTS_CASHFLOWANALYTICS_USER_TYPES_USER_TYPE: DecisioningV2CustomersCustomerIdReportsCashflowAnalyticsUserTypesUserType,
        PathValues.AGGREGATION_V1_CUSTOMERS_CUSTOMER_ID_PAY_STATEMENTS: AggregationV1CustomersCustomerIdPayStatements,
        PathValues.AGGREGATION_V2_CUSTOMERS_CUSTOMER_ID_ACCOUNTS_ACCOUNT_ID_LOAN_DETAILS: AggregationV2CustomersCustomerIdAccountsAccountIdLoanDetails,
        PathValues.DECISIONING_V1_CUSTOMERS_CUSTOMER_ID_PORTFOLIOS_PORTFOLIO_ID: DecisioningV1CustomersCustomerIdPortfoliosPortfolioId,
        PathValues.AGGREGATION_V1_CUSTOMERS_CUSTOMER_ID_ACCOUNTS_ACCOUNT_ID_TXPUSH: AggregationV1CustomersCustomerIdAccountsAccountIdTxpush,
        PathValues.AGGREGATION_V1_CUSTOMERS_CUSTOMER_ID_ACCOUNTS_ACCOUNT_ID_TRANSACTIONS: AggregationV1CustomersCustomerIdAccountsAccountIdTransactions,
        PathValues.AGGREGATION_V1_CUSTOMERS_CUSTOMER_ID_SUBSCRIPTIONS_SUBSCRIPTION_ID: AggregationV1CustomersCustomerIdSubscriptionsSubscriptionId,
        PathValues.DECISIONING_V1_CONSUMERS_CONSUMER_ID_PORTFOLIOS_PORTFOLIO_ID: DecisioningV1ConsumersConsumerIdPortfoliosPortfolioId,
        PathValues.AGGREGATION_V1_CUSTOMERS_CUSTOMER_ID_ACCOUNTS_ACCOUNT_ID_DETAILS: AggregationV1CustomersCustomerIdAccountsAccountIdDetails,
        PathValues.DECISIONING_V3_CUSTOMERS_CUSTOMER_ID_REPORTS_REPORT_ID: DecisioningV3CustomersCustomerIdReportsReportId,
        PathValues.DECISIONING_V3_CONSUMERS_CONSUMER_ID_REPORTS_REPORT_ID: DecisioningV3ConsumersConsumerIdReportsReportId,
        PathValues.DECISIONING_V1_CUSTOMERS_CUSTOMER_ID_REPORTS: DecisioningV1CustomersCustomerIdReports,
        PathValues.DECISIONING_V1_CONSUMERS_CONSUMER_ID_REPORTS: DecisioningV1ConsumersConsumerIdReports,
        PathValues.AGGREGATION_V1_CUSTOMERS_CUSTOMER_ID_ASSETS_ASSET_ID: AggregationV1CustomersCustomerIdAssetsAssetId,
        PathValues.AGGREGATION_V1_CUSTOMERS_CUSTOMER_ID_ACCOUNTS_ACCOUNT_ID_AVAILABLE_BALANCE_LIVE: AggregationV1CustomersCustomerIdAccountsAccountIdAvailableBalanceLive,
        PathValues.AGGREGATION_V1_CUSTOMERS_CUSTOMER_ID_ACCOUNTS_ACCOUNT_ID_AVAILABLE_BALANCE: AggregationV1CustomersCustomerIdAccountsAccountIdAvailableBalance,
        PathValues.DECISIONING_V2_CUSTOMERS_CUSTOMER_ID_CASH_FLOW_BUSINESS: DecisioningV2CustomersCustomerIdCashFlowBusiness,
        PathValues.DECISIONING_V2_CUSTOMERS_CUSTOMER_ID_CASH_FLOW_PERSONAL: DecisioningV2CustomersCustomerIdCashFlowPersonal,
        PathValues.MICROENTRY_V1_CUSTOMERS_CUSTOMER_ID: MicroentryV1CustomersCustomerId,
        PathValues.MICROENTRY_V1_CUSTOMERS_CUSTOMER_ID_ACCOUNTS_ACCOUNT_ID_AMOUNTS: MicroentryV1CustomersCustomerIdAccountsAccountIdAmounts,
        PathValues.MICROENTRY_V1_CUSTOMERS_CUSTOMER_ID_ACCOUNTS_ACCOUNT_ID: MicroentryV1CustomersCustomerIdAccountsAccountId,
        PathValues.ANALYTICS_BALANCE_V1_CUSTOMER_CUSTOMER_ID: AnalyticsBalanceV1CustomerCustomerId,
        PathValues.ANALYTICS_BALANCE_V1_CUSTOMER_CUSTOMER_ID_FCRA: AnalyticsBalanceV1CustomerCustomerIdFcra,
        PathValues.ANALYTICS_CASHFLOW_V1_CUSTOMER_CUSTOMER_ID: AnalyticsCashflowV1CustomerCustomerId,
        PathValues.ANALYTICS_CASHFLOW_V1_CUSTOMER_CUSTOMER_ID_FCRA: AnalyticsCashflowV1CustomerCustomerIdFcra,
        PathValues.ANALYTICS_PAYMENTHISTORY_V1_CUSTOMER_CUSTOMER_ID: AnalyticsPaymentHistoryV1CustomerCustomerId,
        PathValues.ANALYTICS_PAYMENTHISTORY_V1_CUSTOMER_CUSTOMER_ID_FCRA: AnalyticsPaymentHistoryV1CustomerCustomerIdFcra,
        PathValues.ANALYTICS_DATA_V1_OBB_REPORT_ID: AnalyticsDataV1ObbReportId,
        PathValues.ANALYTICS_DATA_V1_OBB_REPORT_ID_FCRA: AnalyticsDataV1ObbReportIdFcra,
        PathValues.AGGREGATION_V1_PARTNERS_ACCESS_KEY: AggregationV1PartnersAccessKey,
        PathValues.AGGREGATION_V1_PARTNERS_ACCESS_KEY_CONSENT_RECEIPT_ID: AggregationV1PartnersAccessKeyConsentReceiptId,
        PathValues.CUSTOMERS_INSTITUTIONLOGINS_INSTITUTION_LOGIN_ID_AUTHORIZATIONDETAILS: CustomersInstitutionLoginsInstitutionLoginIdAuthorizationDetails,
        PathValues.BUSINESSSERVICES_CUSTOMERS_CUSTOMER_ID_BUSINESSES: BusinessServicesCustomersCustomerIdBusinesses,
        PathValues.BUSINESSSERVICES_BUSINESSES_BUSINESS_ID: BusinessServicesBusinessesBusinessId,
    }
)

path_to_api = PathToApi(
    {
        PathValues.AGGREGATION_V2_PARTNERS_AUTHENTICATION: AggregationV2PartnersAuthentication,
        PathValues.CONNECT_V2_GENERATE: ConnectV2Generate,
        PathValues.CONNECT_V2_GENERATE_LITE: ConnectV2GenerateLite,
        PathValues.CONNECT_V2_GENERATE_FIX: ConnectV2GenerateFix,
        PathValues.CONNECT_V2_SEND_EMAIL: ConnectV2SendEmail,
        PathValues.CONNECT_V2_GENERATE_JOINT_BORROWER: ConnectV2GenerateJointBorrower,
        PathValues.CONNECT_V2_GENERATE_MICROENTRY_VERIFY: ConnectV2GenerateMicroentryVerify,
        PathValues.CONNECT_V2_SEND_EMAIL_JOINT_BORROWER: ConnectV2SendEmailJointBorrower,
        PathValues.AGGREGATION_V2_CUSTOMERS_TESTING: AggregationV2CustomersTesting,
        PathValues.AGGREGATION_V2_CUSTOMERS_ACTIVE: AggregationV2CustomersActive,
        PathValues.AGGREGATION_V1_CUSTOMERS: AggregationV1Customers,
        PathValues.AGGREGATION_V1_CUSTOMERS_CUSTOMER_ID_APPLICATION: AggregationV1CustomersCustomerIdApplication,
        PathValues.AGGREGATION_V1_CUSTOMERS_CUSTOMER_ID: AggregationV1CustomersCustomerId,
        PathValues.DECISIONING_V1_CUSTOMERS_CUSTOMER_ID_CONSUMER: DecisioningV1CustomersCustomerIdConsumer,
        PathValues.DECISIONING_V1_CONSUMERS_CONSUMER_ID: DecisioningV1ConsumersConsumerId,
        PathValues.AGGREGATION_V1_CUSTOMERS_CUSTOMER_ID_INSTITUTION_LOGINS_INSTITUTION_LOGIN_ID_ACCOUNTS: AggregationV1CustomersCustomerIdInstitutionLoginsInstitutionLoginIdAccounts,
        PathValues.AGGREGATION_V2_CUSTOMERS_CUSTOMER_ID_INSTITUTION_LOGINS_INSTITUTION_LOGIN_ID_ACCOUNTS: AggregationV2CustomersCustomerIdInstitutionLoginsInstitutionLoginIdAccounts,
        PathValues.AGGREGATION_V1_CUSTOMERS_CUSTOMER_ID_INSTITUTION_LOGINS_INSTITUTION_LOGIN_ID: AggregationV1CustomersCustomerIdInstitutionLoginsInstitutionLoginId,
        PathValues.AGGREGATION_V2_CUSTOMERS_CUSTOMER_ID_ACCOUNTS_ACCOUNT_ID: AggregationV2CustomersCustomerIdAccountsAccountId,
        PathValues.AGGREGATION_V1_CUSTOMERS_CUSTOMER_ID_ACCOUNTS_ACCOUNT_ID: AggregationV1CustomersCustomerIdAccountsAccountId,
        PathValues.AGGREGATION_V1_CUSTOMERS_CUSTOMER_ID_ACCOUNTS: AggregationV1CustomersCustomerIdAccounts,
        PathValues.AGGREGATION_V2_CUSTOMERS_CUSTOMER_ID_ACCOUNTS: AggregationV2CustomersCustomerIdAccounts,
        PathValues.AGGREGATION_V1_CUSTOMERS_CUSTOMER_ID_INSTITUTIONS_INSTITUTION_ID_ACCOUNTS: AggregationV1CustomersCustomerIdInstitutionsInstitutionIdAccounts,
        PathValues.AGGREGATION_V1_CUSTOMERS_CUSTOMER_ID_INSTITUTIONS_INSTITUTION_ID_ACCOUNTS_SIMPLE: AggregationV1CustomersCustomerIdInstitutionsInstitutionIdAccountsSimple,
        PathValues.AGGREGATION_V1_CUSTOMERS_CUSTOMER_ID_INSTITUTION_LOGINS_INSTITUTION_LOGIN_ID_ACCOUNTS_SIMPLE: AggregationV1CustomersCustomerIdInstitutionLoginsInstitutionLoginIdAccountsSimple,
        PathValues.AGGREGATION_V1_CUSTOMERS_CUSTOMER_ID_ACCOUNTS_ACCOUNT_ID_SIMPLE: AggregationV1CustomersCustomerIdAccountsAccountIdSimple,
        PathValues.AGGREGATION_V1_CUSTOMERS_CUSTOMER_ID_ACCOUNTS_SIMPLE: AggregationV1CustomersCustomerIdAccountsSimple,
        PathValues.AGGREGATION_V1_CUSTOMERS_CUSTOMER_ID_ACCOUNTS_ACCOUNT_ID_TRANSACTIONS_HISTORIC: AggregationV1CustomersCustomerIdAccountsAccountIdTransactionsHistoric,
        PathValues.AGGREGATION_V1_CUSTOMERS_CUSTOMER_ID_ACCOUNTS_ACCOUNT_ID_OWNER: AggregationV1CustomersCustomerIdAccountsAccountIdOwner,
        PathValues.AGGREGATION_V3_CUSTOMERS_CUSTOMER_ID_ACCOUNTS_ACCOUNT_ID_OWNER: AggregationV3CustomersCustomerIdAccountsAccountIdOwner,
        PathValues.AGGREGATION_V1_PARTNERS_APPLICATIONS: AggregationV1PartnersApplications,
        PathValues.AGGREGATION_V1_PARTNERS_APPLICATIONS_PRE_APP_ID: AggregationV1PartnersApplicationsPreAppId,
        PathValues.AGGREGATION_V2_PARTNERS_APPLICATIONS: AggregationV2PartnersApplications,
        PathValues.AGGREGATION_V1_CUSTOMERS_CUSTOMER_ID_APPLICATIONS_APPLICATION_ID: AggregationV1CustomersCustomerIdApplicationsApplicationId,
        PathValues.AGGREGATION_V2_CUSTOMERS_CUSTOMER_ID_INSTITUTION_LOGINS_INSTITUTION_LOGIN_ID_MIGRATION: AggregationV2CustomersCustomerIdInstitutionLoginsInstitutionLoginIdMigration,
        PathValues.INSTITUTION_V2_CERTIFIED_INSTITUTIONS_RSSD: InstitutionV2CertifiedInstitutionsRssd,
        PathValues.INSTITUTION_V2_INSTITUTIONS: InstitutionV2Institutions,
        PathValues.INSTITUTION_V2_CERTIFIED_INSTITUTIONS: InstitutionV2CertifiedInstitutions,
        PathValues.INSTITUTION_V2_INSTITUTIONS_INSTITUTION_ID: InstitutionV2InstitutionsInstitutionId,
        PathValues.INSTITUTION_V2_INSTITUTIONS_INSTITUTION_ID_BRANDING: InstitutionV2InstitutionsInstitutionIdBranding,
        PathValues.DECISIONING_V2_CUSTOMERS_CUSTOMER_ID_VOA: DecisioningV2CustomersCustomerIdVoa,
        PathValues.DECISIONING_V2_CUSTOMERS_CUSTOMER_ID_VOA_HISTORY: DecisioningV2CustomersCustomerIdVoaHistory,
        PathValues.DECISIONING_V2_CUSTOMERS_CUSTOMER_ID_PRE_QUAL_VOA: DecisioningV2CustomersCustomerIdPreQualVoa,
        PathValues.DECISIONING_V2_CUSTOMERS_CUSTOMER_ID_ASSET_SUMMARY: DecisioningV2CustomersCustomerIdAssetSummary,
        PathValues.DECISIONING_V2_CUSTOMERS_CUSTOMER_ID_VOI: DecisioningV2CustomersCustomerIdVoi,
        PathValues.DECISIONING_V2_CUSTOMERS_CUSTOMER_ID_VOE_PAYROLL: DecisioningV2CustomersCustomerIdVoePayroll,
        PathValues.DECISIONING_V2_CUSTOMERS_CUSTOMER_ID_VOE_TRANSACTIONS: DecisioningV2CustomersCustomerIdVoeTransactions,
        PathValues.DECISIONING_V2_CUSTOMERS_CUSTOMER_ID_PAY_STATEMENT: DecisioningV2CustomersCustomerIdPayStatement,
        PathValues.DECISIONING_V2_CUSTOMERS_CUSTOMER_ID_VOIE_TX_VERIFY_WITH_INTERVIEW: DecisioningV2CustomersCustomerIdVoieTxVerifyWithInterview,
        PathValues.DECISIONING_V2_CUSTOMERS_CUSTOMER_ID_VOIE_TX_VERIFY_WITH_STATEMENT: DecisioningV2CustomersCustomerIdVoieTxVerifyWithStatement,
        PathValues.DECISIONING_V2_CUSTOMERS_CUSTOMER_ID_VOIE_PAYROLL: DecisioningV2CustomersCustomerIdVoiePayroll,
        PathValues.AGGREGATION_V1_CUSTOMERS_CUSTOMER_ID_ACCOUNTS_ACCOUNT_ID_STATEMENT: AggregationV1CustomersCustomerIdAccountsAccountIdStatement,
        PathValues.DECISIONING_V2_CUSTOMERS_CUSTOMER_ID_STATEMENT: DecisioningV2CustomersCustomerIdStatement,
        PathValues.AGGREGATION_V3_CUSTOMERS_CUSTOMER_ID_ACCOUNTS_ACCOUNT_ID_STATEMENT: AggregationV3CustomersCustomerIdAccountsAccountIdStatement,
        PathValues.AGGREGATION_V3_CUSTOMERS_CUSTOMER_ID_TRANSACTIONS: AggregationV3CustomersCustomerIdTransactions,
        PathValues.AGGREGATION_V2_CUSTOMERS_CUSTOMER_ID_TRANSACTIONS_TRANSACTION_ID: AggregationV2CustomersCustomerIdTransactionsTransactionId,
        PathValues.AGGREGATION_V4_CUSTOMERS_CUSTOMER_ID_ACCOUNTS_ACCOUNT_ID_TRANSACTIONS: AggregationV4CustomersCustomerIdAccountsAccountIdTransactions,
        PathValues.DECISIONING_V2_CUSTOMERS_CUSTOMER_ID_TRANSACTIONS: DecisioningV2CustomersCustomerIdTransactions,
        PathValues.DECISIONING_V2_CUSTOMERS_CUSTOMER_ID_REPORTS_BALANCEANALYTICS_USER_TYPES_USER_TYPE: DecisioningV2CustomersCustomerIdReportsBalanceAnalyticsUserTypesUserType,
        PathValues.DECISIONING_V2_CUSTOMERS_CUSTOMER_ID_REPORTS_CASHFLOWANALYTICS_USER_TYPES_USER_TYPE: DecisioningV2CustomersCustomerIdReportsCashflowAnalyticsUserTypesUserType,
        PathValues.AGGREGATION_V1_CUSTOMERS_CUSTOMER_ID_PAY_STATEMENTS: AggregationV1CustomersCustomerIdPayStatements,
        PathValues.AGGREGATION_V2_CUSTOMERS_CUSTOMER_ID_ACCOUNTS_ACCOUNT_ID_LOAN_DETAILS: AggregationV2CustomersCustomerIdAccountsAccountIdLoanDetails,
        PathValues.DECISIONING_V1_CUSTOMERS_CUSTOMER_ID_PORTFOLIOS_PORTFOLIO_ID: DecisioningV1CustomersCustomerIdPortfoliosPortfolioId,
        PathValues.AGGREGATION_V1_CUSTOMERS_CUSTOMER_ID_ACCOUNTS_ACCOUNT_ID_TXPUSH: AggregationV1CustomersCustomerIdAccountsAccountIdTxpush,
        PathValues.AGGREGATION_V1_CUSTOMERS_CUSTOMER_ID_ACCOUNTS_ACCOUNT_ID_TRANSACTIONS: AggregationV1CustomersCustomerIdAccountsAccountIdTransactions,
        PathValues.AGGREGATION_V1_CUSTOMERS_CUSTOMER_ID_SUBSCRIPTIONS_SUBSCRIPTION_ID: AggregationV1CustomersCustomerIdSubscriptionsSubscriptionId,
        PathValues.DECISIONING_V1_CONSUMERS_CONSUMER_ID_PORTFOLIOS_PORTFOLIO_ID: DecisioningV1ConsumersConsumerIdPortfoliosPortfolioId,
        PathValues.AGGREGATION_V1_CUSTOMERS_CUSTOMER_ID_ACCOUNTS_ACCOUNT_ID_DETAILS: AggregationV1CustomersCustomerIdAccountsAccountIdDetails,
        PathValues.DECISIONING_V3_CUSTOMERS_CUSTOMER_ID_REPORTS_REPORT_ID: DecisioningV3CustomersCustomerIdReportsReportId,
        PathValues.DECISIONING_V3_CONSUMERS_CONSUMER_ID_REPORTS_REPORT_ID: DecisioningV3ConsumersConsumerIdReportsReportId,
        PathValues.DECISIONING_V1_CUSTOMERS_CUSTOMER_ID_REPORTS: DecisioningV1CustomersCustomerIdReports,
        PathValues.DECISIONING_V1_CONSUMERS_CONSUMER_ID_REPORTS: DecisioningV1ConsumersConsumerIdReports,
        PathValues.AGGREGATION_V1_CUSTOMERS_CUSTOMER_ID_ASSETS_ASSET_ID: AggregationV1CustomersCustomerIdAssetsAssetId,
        PathValues.AGGREGATION_V1_CUSTOMERS_CUSTOMER_ID_ACCOUNTS_ACCOUNT_ID_AVAILABLE_BALANCE_LIVE: AggregationV1CustomersCustomerIdAccountsAccountIdAvailableBalanceLive,
        PathValues.AGGREGATION_V1_CUSTOMERS_CUSTOMER_ID_ACCOUNTS_ACCOUNT_ID_AVAILABLE_BALANCE: AggregationV1CustomersCustomerIdAccountsAccountIdAvailableBalance,
        PathValues.DECISIONING_V2_CUSTOMERS_CUSTOMER_ID_CASH_FLOW_BUSINESS: DecisioningV2CustomersCustomerIdCashFlowBusiness,
        PathValues.DECISIONING_V2_CUSTOMERS_CUSTOMER_ID_CASH_FLOW_PERSONAL: DecisioningV2CustomersCustomerIdCashFlowPersonal,
        PathValues.MICROENTRY_V1_CUSTOMERS_CUSTOMER_ID: MicroentryV1CustomersCustomerId,
        PathValues.MICROENTRY_V1_CUSTOMERS_CUSTOMER_ID_ACCOUNTS_ACCOUNT_ID_AMOUNTS: MicroentryV1CustomersCustomerIdAccountsAccountIdAmounts,
        PathValues.MICROENTRY_V1_CUSTOMERS_CUSTOMER_ID_ACCOUNTS_ACCOUNT_ID: MicroentryV1CustomersCustomerIdAccountsAccountId,
        PathValues.ANALYTICS_BALANCE_V1_CUSTOMER_CUSTOMER_ID: AnalyticsBalanceV1CustomerCustomerId,
        PathValues.ANALYTICS_BALANCE_V1_CUSTOMER_CUSTOMER_ID_FCRA: AnalyticsBalanceV1CustomerCustomerIdFcra,
        PathValues.ANALYTICS_CASHFLOW_V1_CUSTOMER_CUSTOMER_ID: AnalyticsCashflowV1CustomerCustomerId,
        PathValues.ANALYTICS_CASHFLOW_V1_CUSTOMER_CUSTOMER_ID_FCRA: AnalyticsCashflowV1CustomerCustomerIdFcra,
        PathValues.ANALYTICS_PAYMENTHISTORY_V1_CUSTOMER_CUSTOMER_ID: AnalyticsPaymentHistoryV1CustomerCustomerId,
        PathValues.ANALYTICS_PAYMENTHISTORY_V1_CUSTOMER_CUSTOMER_ID_FCRA: AnalyticsPaymentHistoryV1CustomerCustomerIdFcra,
        PathValues.ANALYTICS_DATA_V1_OBB_REPORT_ID: AnalyticsDataV1ObbReportId,
        PathValues.ANALYTICS_DATA_V1_OBB_REPORT_ID_FCRA: AnalyticsDataV1ObbReportIdFcra,
        PathValues.AGGREGATION_V1_PARTNERS_ACCESS_KEY: AggregationV1PartnersAccessKey,
        PathValues.AGGREGATION_V1_PARTNERS_ACCESS_KEY_CONSENT_RECEIPT_ID: AggregationV1PartnersAccessKeyConsentReceiptId,
        PathValues.CUSTOMERS_INSTITUTIONLOGINS_INSTITUTION_LOGIN_ID_AUTHORIZATIONDETAILS: CustomersInstitutionLoginsInstitutionLoginIdAuthorizationDetails,
        PathValues.BUSINESSSERVICES_CUSTOMERS_CUSTOMER_ID_BUSINESSES: BusinessServicesCustomersCustomerIdBusinesses,
        PathValues.BUSINESSSERVICES_BUSINESSES_BUSINESS_ID: BusinessServicesBusinessesBusinessId,
    }
)
