from mastercard_python_sdk.paths.aggregation_v1_customers_customer_id_institution_logins_institution_login_id_accounts.get import ApiForget
from mastercard_python_sdk.paths.aggregation_v1_customers_customer_id_institution_logins_institution_login_id_accounts.post import ApiForpost


class AggregationV1CustomersCustomerIdInstitutionLoginsInstitutionLoginIdAccounts(
    ApiForget,
    ApiForpost,
):
    pass
