from mastercard_python_sdk.paths.aggregation_v1_customers_customer_id_institution_logins_institution_login_id_accounts_simple.get import ApiForget


class AggregationV1CustomersCustomerIdInstitutionLoginsInstitutionLoginIdAccountsSimple(
    ApiForget,
):
    pass
