# coding: utf-8

"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.16.0
    Contact: apisupport@mastercard.com
    Created by: https://developer.mastercard.com/open-banking-us/documentation/support/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from mastercard_python_sdk import schemas  # noqa: F401


class AnalyticsReportData(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Parameters supplied by the client requesting the analytics.
    """


    class MetaOapg:
        required = {
            "forCraPurpose",
        }
        
        class properties:
            forCraPurpose = schemas.BoolSchema
            applicantIsPersonalGuarantor = schemas.BoolSchema
            
            
            class timeIntervalTypes(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    items = schemas.StrSchema
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, str, ]], typing.List[typing.Union[MetaOapg.items, str, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'timeIntervalTypes':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
            __annotations__ = {
                "forCraPurpose": forCraPurpose,
                "applicantIsPersonalGuarantor": applicantIsPersonalGuarantor,
                "timeIntervalTypes": timeIntervalTypes,
            }
    
    forCraPurpose: MetaOapg.properties.forCraPurpose
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["forCraPurpose"]) -> MetaOapg.properties.forCraPurpose: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["applicantIsPersonalGuarantor"]) -> MetaOapg.properties.applicantIsPersonalGuarantor: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["timeIntervalTypes"]) -> MetaOapg.properties.timeIntervalTypes: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["forCraPurpose", "applicantIsPersonalGuarantor", "timeIntervalTypes", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["forCraPurpose"]) -> MetaOapg.properties.forCraPurpose: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["applicantIsPersonalGuarantor"]) -> typing.Union[MetaOapg.properties.applicantIsPersonalGuarantor, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["timeIntervalTypes"]) -> typing.Union[MetaOapg.properties.timeIntervalTypes, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["forCraPurpose", "applicantIsPersonalGuarantor", "timeIntervalTypes", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        forCraPurpose: typing.Union[MetaOapg.properties.forCraPurpose, bool, ],
        applicantIsPersonalGuarantor: typing.Union[MetaOapg.properties.applicantIsPersonalGuarantor, bool, schemas.Unset] = schemas.unset,
        timeIntervalTypes: typing.Union[MetaOapg.properties.timeIntervalTypes, list, tuple, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'AnalyticsReportData':
        return super().__new__(
            cls,
            *args,
            forCraPurpose=forCraPurpose,
            applicantIsPersonalGuarantor=applicantIsPersonalGuarantor,
            timeIntervalTypes=timeIntervalTypes,
            _configuration=_configuration,
            **kwargs,
        )
