# coding: utf-8

"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.16.0
    Contact: apisupport@mastercard.com
    Created by: https://developer.mastercard.com/open-banking-us/documentation/support/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from mastercard_python_sdk import schemas  # noqa: F401


class BalanceAndCashFlowAnalyticsReportConstraints(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Request parameters from the partner to control the customer accounts included in the report, and the length of time to report on.
    """


    class MetaOapg:
        
        class properties:
            
            
            class accountIds(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    items = schemas.Int64Schema
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, decimal.Decimal, int, ]], typing.List[typing.Union[MetaOapg.items, decimal.Decimal, int, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'accountIds':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
            lengthOfReport = schemas.IntSchema
            __annotations__ = {
                "accountIds": accountIds,
                "lengthOfReport": lengthOfReport,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["accountIds"]) -> MetaOapg.properties.accountIds: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["lengthOfReport"]) -> MetaOapg.properties.lengthOfReport: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["accountIds", "lengthOfReport", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["accountIds"]) -> typing.Union[MetaOapg.properties.accountIds, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["lengthOfReport"]) -> typing.Union[MetaOapg.properties.lengthOfReport, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["accountIds", "lengthOfReport", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        accountIds: typing.Union[MetaOapg.properties.accountIds, list, tuple, schemas.Unset] = schemas.unset,
        lengthOfReport: typing.Union[MetaOapg.properties.lengthOfReport, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'BalanceAndCashFlowAnalyticsReportConstraints':
        return super().__new__(
            cls,
            *args,
            accountIds=accountIds,
            lengthOfReport=lengthOfReport,
            _configuration=_configuration,
            **kwargs,
        )
