# coding: utf-8

"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.16.0
    Contact: apisupport@mastercard.com
    Created by: https://developer.mastercard.com/open-banking-us/documentation/support/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from mastercard_python_sdk import schemas  # noqa: F401


class CashFlowInsufficientFundsFees(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Non-Sufficient Fund Fees
    """


    class MetaOapg:
        
        class properties:
            countOfTransactionsForTheReportTimePeriod = schemas.IntSchema
            sumOfTransactionsForTheReportTimePeriod = schemas.NumberSchema
            
            
            class transactions(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['InsufficientFundsTransaction']:
                        return InsufficientFundsTransaction
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['InsufficientFundsTransaction'], typing.List['InsufficientFundsTransaction']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'transactions':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'InsufficientFundsTransaction':
                    return super().__getitem__(i)
            __annotations__ = {
                "countOfTransactionsForTheReportTimePeriod": countOfTransactionsForTheReportTimePeriod,
                "sumOfTransactionsForTheReportTimePeriod": sumOfTransactionsForTheReportTimePeriod,
                "transactions": transactions,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["countOfTransactionsForTheReportTimePeriod"]) -> MetaOapg.properties.countOfTransactionsForTheReportTimePeriod: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["sumOfTransactionsForTheReportTimePeriod"]) -> MetaOapg.properties.sumOfTransactionsForTheReportTimePeriod: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["transactions"]) -> MetaOapg.properties.transactions: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["countOfTransactionsForTheReportTimePeriod", "sumOfTransactionsForTheReportTimePeriod", "transactions", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["countOfTransactionsForTheReportTimePeriod"]) -> typing.Union[MetaOapg.properties.countOfTransactionsForTheReportTimePeriod, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["sumOfTransactionsForTheReportTimePeriod"]) -> typing.Union[MetaOapg.properties.sumOfTransactionsForTheReportTimePeriod, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["transactions"]) -> typing.Union[MetaOapg.properties.transactions, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["countOfTransactionsForTheReportTimePeriod", "sumOfTransactionsForTheReportTimePeriod", "transactions", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        countOfTransactionsForTheReportTimePeriod: typing.Union[MetaOapg.properties.countOfTransactionsForTheReportTimePeriod, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        sumOfTransactionsForTheReportTimePeriod: typing.Union[MetaOapg.properties.sumOfTransactionsForTheReportTimePeriod, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        transactions: typing.Union[MetaOapg.properties.transactions, list, tuple, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'CashFlowInsufficientFundsFees':
        return super().__new__(
            cls,
            *args,
            countOfTransactionsForTheReportTimePeriod=countOfTransactionsForTheReportTimePeriod,
            sumOfTransactionsForTheReportTimePeriod=sumOfTransactionsForTheReportTimePeriod,
            transactions=transactions,
            _configuration=_configuration,
            **kwargs,
        )

from mastercard_python_sdk.model.insufficient_funds_transaction import InsufficientFundsTransaction
