# coding: utf-8

"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.16.0
    Contact: apisupport@mastercard.com
    Created by: https://developer.mastercard.com/open-banking-us/documentation/support/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from mastercard_python_sdk import schemas  # noqa: F401


class ReportIncomeEstimate(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "netAnnual",
            "projectedNetAnnual",
            "projectedGrossAnnual",
            "estimatedGrossAnnual",
        }
        
        class properties:
            netAnnual = schemas.NumberSchema
            projectedNetAnnual = schemas.NumberSchema
            estimatedGrossAnnual = schemas.NumberSchema
            projectedGrossAnnual = schemas.NumberSchema
            __annotations__ = {
                "netAnnual": netAnnual,
                "projectedNetAnnual": projectedNetAnnual,
                "estimatedGrossAnnual": estimatedGrossAnnual,
                "projectedGrossAnnual": projectedGrossAnnual,
            }
    
    netAnnual: MetaOapg.properties.netAnnual
    projectedNetAnnual: MetaOapg.properties.projectedNetAnnual
    projectedGrossAnnual: MetaOapg.properties.projectedGrossAnnual
    estimatedGrossAnnual: MetaOapg.properties.estimatedGrossAnnual
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["netAnnual"]) -> MetaOapg.properties.netAnnual: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["projectedNetAnnual"]) -> MetaOapg.properties.projectedNetAnnual: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["estimatedGrossAnnual"]) -> MetaOapg.properties.estimatedGrossAnnual: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["projectedGrossAnnual"]) -> MetaOapg.properties.projectedGrossAnnual: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["netAnnual", "projectedNetAnnual", "estimatedGrossAnnual", "projectedGrossAnnual", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["netAnnual"]) -> MetaOapg.properties.netAnnual: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["projectedNetAnnual"]) -> MetaOapg.properties.projectedNetAnnual: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["estimatedGrossAnnual"]) -> MetaOapg.properties.estimatedGrossAnnual: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["projectedGrossAnnual"]) -> MetaOapg.properties.projectedGrossAnnual: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["netAnnual", "projectedNetAnnual", "estimatedGrossAnnual", "projectedGrossAnnual", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        netAnnual: typing.Union[MetaOapg.properties.netAnnual, decimal.Decimal, int, float, ],
        projectedNetAnnual: typing.Union[MetaOapg.properties.projectedNetAnnual, decimal.Decimal, int, float, ],
        projectedGrossAnnual: typing.Union[MetaOapg.properties.projectedGrossAnnual, decimal.Decimal, int, float, ],
        estimatedGrossAnnual: typing.Union[MetaOapg.properties.estimatedGrossAnnual, decimal.Decimal, int, float, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ReportIncomeEstimate':
        return super().__new__(
            cls,
            *args,
            netAnnual=netAnnual,
            projectedNetAnnual=projectedNetAnnual,
            projectedGrossAnnual=projectedGrossAnnual,
            estimatedGrossAnnual=estimatedGrossAnnual,
            _configuration=_configuration,
            **kwargs,
        )
