# coding: utf-8

"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.16.0
    Contact: apisupport@mastercard.com
    Created by: https://developer.mastercard.com/open-banking-us/documentation/support/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from mastercard_python_sdk import schemas  # noqa: F401


class TransactionalTimeInterval(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    For a TransactionalAttribute, describes a time interval type being reported
and a list of periods generated according to that type.
    """


    class MetaOapg:
        required = {
            "periods",
            "timeIntervalType",
        }
        
        class properties:
            
            
            class periods(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['TransactionalPeriod']:
                        return TransactionalPeriod
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['TransactionalPeriod'], typing.List['TransactionalPeriod']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'periods':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'TransactionalPeriod':
                    return super().__getitem__(i)
            timeIntervalType = schemas.StrSchema
            __annotations__ = {
                "periods": periods,
                "timeIntervalType": timeIntervalType,
            }
    
    periods: MetaOapg.properties.periods
    timeIntervalType: MetaOapg.properties.timeIntervalType
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["periods"]) -> MetaOapg.properties.periods: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["timeIntervalType"]) -> MetaOapg.properties.timeIntervalType: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["periods", "timeIntervalType", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["periods"]) -> MetaOapg.properties.periods: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["timeIntervalType"]) -> MetaOapg.properties.timeIntervalType: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["periods", "timeIntervalType", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        periods: typing.Union[MetaOapg.properties.periods, list, tuple, ],
        timeIntervalType: typing.Union[MetaOapg.properties.timeIntervalType, str, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'TransactionalTimeInterval':
        return super().__new__(
            cls,
            *args,
            periods=periods,
            timeIntervalType=timeIntervalType,
            _configuration=_configuration,
            **kwargs,
        )

from mastercard_python_sdk.model.transactional_period import TransactionalPeriod
