# coding: utf-8

"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.16.0
    Contact: apisupport@mastercard.com
    Created by: https://developer.mastercard.com/open-banking-us/documentation/support/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from mastercard_python_sdk import schemas  # noqa: F401


class VOAIReportIncomeStream(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    A report income stream record
    """


    class MetaOapg:
        required = {
            "confidence",
            "estimateInclusion",
            "name",
            "id",
            "transactions",
            "cadence",
            "status",
        }
        
        class properties:
            id = schemas.StrSchema
            name = schemas.StrSchema
            status = schemas.StrSchema
            estimateInclusion = schemas.StrSchema
            confidence = schemas.Int32Schema
        
            @staticmethod
            def cadence() -> typing.Type['CadenceDetails']:
                return CadenceDetails
            
            
            class transactions(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['ReportTransaction']:
                        return ReportTransaction
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['ReportTransaction'], typing.List['ReportTransaction']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'transactions':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'ReportTransaction':
                    return super().__getitem__(i)
            
            
            class netMonthly(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['NetMonthly']:
                        return NetMonthly
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['NetMonthly'], typing.List['NetMonthly']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'netMonthly':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'NetMonthly':
                    return super().__getitem__(i)
            netAnnual = schemas.NumberSchema
            projectedNetAnnual = schemas.NumberSchema
            estimatedGrossAnnual = schemas.NumberSchema
            projectedGrossAnnual = schemas.NumberSchema
            averageMonthlyIncomeNet = schemas.NumberSchema
            incomeStreamMonths = schemas.Int32Schema
            __annotations__ = {
                "id": id,
                "name": name,
                "status": status,
                "estimateInclusion": estimateInclusion,
                "confidence": confidence,
                "cadence": cadence,
                "transactions": transactions,
                "netMonthly": netMonthly,
                "netAnnual": netAnnual,
                "projectedNetAnnual": projectedNetAnnual,
                "estimatedGrossAnnual": estimatedGrossAnnual,
                "projectedGrossAnnual": projectedGrossAnnual,
                "averageMonthlyIncomeNet": averageMonthlyIncomeNet,
                "incomeStreamMonths": incomeStreamMonths,
            }
    
    confidence: MetaOapg.properties.confidence
    estimateInclusion: MetaOapg.properties.estimateInclusion
    name: MetaOapg.properties.name
    id: MetaOapg.properties.id
    transactions: MetaOapg.properties.transactions
    cadence: 'CadenceDetails'
    status: MetaOapg.properties.status
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["status"]) -> MetaOapg.properties.status: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["estimateInclusion"]) -> MetaOapg.properties.estimateInclusion: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["confidence"]) -> MetaOapg.properties.confidence: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cadence"]) -> 'CadenceDetails': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["transactions"]) -> MetaOapg.properties.transactions: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["netMonthly"]) -> MetaOapg.properties.netMonthly: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["netAnnual"]) -> MetaOapg.properties.netAnnual: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["projectedNetAnnual"]) -> MetaOapg.properties.projectedNetAnnual: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["estimatedGrossAnnual"]) -> MetaOapg.properties.estimatedGrossAnnual: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["projectedGrossAnnual"]) -> MetaOapg.properties.projectedGrossAnnual: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["averageMonthlyIncomeNet"]) -> MetaOapg.properties.averageMonthlyIncomeNet: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["incomeStreamMonths"]) -> MetaOapg.properties.incomeStreamMonths: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["id", "name", "status", "estimateInclusion", "confidence", "cadence", "transactions", "netMonthly", "netAnnual", "projectedNetAnnual", "estimatedGrossAnnual", "projectedGrossAnnual", "averageMonthlyIncomeNet", "incomeStreamMonths", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["status"]) -> MetaOapg.properties.status: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["estimateInclusion"]) -> MetaOapg.properties.estimateInclusion: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["confidence"]) -> MetaOapg.properties.confidence: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cadence"]) -> 'CadenceDetails': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["transactions"]) -> MetaOapg.properties.transactions: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["netMonthly"]) -> typing.Union[MetaOapg.properties.netMonthly, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["netAnnual"]) -> typing.Union[MetaOapg.properties.netAnnual, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["projectedNetAnnual"]) -> typing.Union[MetaOapg.properties.projectedNetAnnual, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["estimatedGrossAnnual"]) -> typing.Union[MetaOapg.properties.estimatedGrossAnnual, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["projectedGrossAnnual"]) -> typing.Union[MetaOapg.properties.projectedGrossAnnual, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["averageMonthlyIncomeNet"]) -> typing.Union[MetaOapg.properties.averageMonthlyIncomeNet, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["incomeStreamMonths"]) -> typing.Union[MetaOapg.properties.incomeStreamMonths, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["id", "name", "status", "estimateInclusion", "confidence", "cadence", "transactions", "netMonthly", "netAnnual", "projectedNetAnnual", "estimatedGrossAnnual", "projectedGrossAnnual", "averageMonthlyIncomeNet", "incomeStreamMonths", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        confidence: typing.Union[MetaOapg.properties.confidence, decimal.Decimal, int, ],
        estimateInclusion: typing.Union[MetaOapg.properties.estimateInclusion, str, ],
        name: typing.Union[MetaOapg.properties.name, str, ],
        id: typing.Union[MetaOapg.properties.id, str, ],
        transactions: typing.Union[MetaOapg.properties.transactions, list, tuple, ],
        cadence: 'CadenceDetails',
        status: typing.Union[MetaOapg.properties.status, str, ],
        netMonthly: typing.Union[MetaOapg.properties.netMonthly, list, tuple, schemas.Unset] = schemas.unset,
        netAnnual: typing.Union[MetaOapg.properties.netAnnual, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        projectedNetAnnual: typing.Union[MetaOapg.properties.projectedNetAnnual, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        estimatedGrossAnnual: typing.Union[MetaOapg.properties.estimatedGrossAnnual, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        projectedGrossAnnual: typing.Union[MetaOapg.properties.projectedGrossAnnual, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        averageMonthlyIncomeNet: typing.Union[MetaOapg.properties.averageMonthlyIncomeNet, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        incomeStreamMonths: typing.Union[MetaOapg.properties.incomeStreamMonths, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'VOAIReportIncomeStream':
        return super().__new__(
            cls,
            *args,
            confidence=confidence,
            estimateInclusion=estimateInclusion,
            name=name,
            id=id,
            transactions=transactions,
            cadence=cadence,
            status=status,
            netMonthly=netMonthly,
            netAnnual=netAnnual,
            projectedNetAnnual=projectedNetAnnual,
            estimatedGrossAnnual=estimatedGrossAnnual,
            projectedGrossAnnual=projectedGrossAnnual,
            averageMonthlyIncomeNet=averageMonthlyIncomeNet,
            incomeStreamMonths=incomeStreamMonths,
            _configuration=_configuration,
            **kwargs,
        )

from mastercard_python_sdk.model.cadence_details import CadenceDetails
from mastercard_python_sdk.model.net_monthly import NetMonthly
from mastercard_python_sdk.model.report_transaction import ReportTransaction
