# coding: utf-8

"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.16.0
    Contact: apisupport@mastercard.com
    Created by: https://developer.mastercard.com/open-banking-us/documentation/support/
"""

from mastercard_python_sdk.paths.decisioning_v2_customers_customer_id_statement.post import GenerateReportRaw
from mastercard_python_sdk.paths.aggregation_v1_customers_customer_id_accounts_account_id_statement.get import GetCustomerStatementInPdfRaw
from mastercard_python_sdk.paths.aggregation_v3_customers_customer_id_accounts_account_id_statement.get import GetMultipleStatementsRaw


class BankStatementsApiRaw(
    GenerateReportRaw,
    GetCustomerStatementInPdfRaw,
    GetMultipleStatementsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
