# coding: utf-8

"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.16.0
    Contact: apisupport@mastercard.com
    Created by: https://developer.mastercard.com/open-banking-us/documentation/support/
"""

from mastercard_python_sdk.paths.decisioning_v2_customers_customer_id_statement.post import GenerateReport
from mastercard_python_sdk.paths.aggregation_v1_customers_customer_id_accounts_account_id_statement.get import GetCustomerStatementInPdf
from mastercard_python_sdk.paths.aggregation_v3_customers_customer_id_accounts_account_id_statement.get import GetMultipleStatements
from mastercard_python_sdk.apis.tags.bank_statements_api_raw import BankStatementsApiRaw


class BankStatementsApi(
    GenerateReport,
    GetCustomerStatementInPdf,
    GetMultipleStatements,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: BankStatementsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = BankStatementsApiRaw(api_client)
