# coding: utf-8

"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.16.0
    Contact: apisupport@mastercard.com
    Created by: https://developer.mastercard.com/open-banking-us/documentation/support/
"""

from mastercard_python_sdk.paths.connect_v2_generate_fix.post import FixUrlGeneration
from mastercard_python_sdk.paths.connect_v2_generate_joint_borrower.post import GenerateJointBorrowerUrl
from mastercard_python_sdk.paths.connect_v2_generate_lite.post import GenerateLiteUrl
from mastercard_python_sdk.paths.connect_v2_generate.post import GenerateUrl
from mastercard_python_sdk.paths.connect_v2_send_email.post import SendConnectEmail
from mastercard_python_sdk.paths.connect_v2_send_email_joint_borrower.post import SendEmailJointBorrower
from mastercard_python_sdk.paths.connect_v2_generate_microentry_verify.post import VerifyMicroEntryMicrodeposits
from mastercard_python_sdk.apis.tags.connect_api_raw import ConnectApiRaw


class ConnectApi(
    FixUrlGeneration,
    GenerateJointBorrowerUrl,
    GenerateLiteUrl,
    GenerateUrl,
    SendConnectEmail,
    SendEmailJointBorrower,
    VerifyMicroEntryMicrodeposits,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ConnectApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ConnectApiRaw(api_client)
