# coding: utf-8

"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.16.0
    Contact: apisupport@mastercard.com
    Created by: https://developer.mastercard.com/open-banking-us/documentation/support/
"""

from mastercard_python_sdk.paths.decisioning_v1_customers_customer_id_consumer.post import CreateConsumerRecordRaw
from mastercard_python_sdk.paths.decisioning_v1_customers_customer_id_consumer.get import GetByCustomerIdRaw
from mastercard_python_sdk.paths.decisioning_v1_consumers_consumer_id.get import GetByIdRaw
from mastercard_python_sdk.paths.decisioning_v1_consumers_consumer_id.put import ModifyByIdRaw


class ConsumersApiRaw(
    CreateConsumerRecordRaw,
    GetByCustomerIdRaw,
    GetByIdRaw,
    ModifyByIdRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
