# coding: utf-8

"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.16.0
    Contact: apisupport@mastercard.com
    Created by: https://developer.mastercard.com/open-banking-us/documentation/support/
"""

from mastercard_python_sdk.paths.aggregation_v1_customers_customer_id_accounts_account_id_owner.get import GetAccountOwnerDetails
from mastercard_python_sdk.paths.aggregation_v3_customers_customer_id_accounts_account_id_owner.get import GetAccountOwnerDetails0
from mastercard_python_sdk.paths.aggregation_v1_customers_customer_id_accounts_account_id_details.get import GetAchDetails
from mastercard_python_sdk.paths.aggregation_v1_customers_customer_id_accounts_account_id_available_balance_live.get import GetAvailableBalanceLive
from mastercard_python_sdk.paths.aggregation_v1_customers_customer_id_accounts_account_id_available_balance.get import GetLatestCachedBalance
from mastercard_python_sdk.paths.aggregation_v2_customers_customer_id_accounts_account_id_loan_details.get import GetLoanPaymentDetails
from mastercard_python_sdk.apis.tags.payments_api_raw import PaymentsApiRaw


class PaymentsApi(
    GetAccountOwnerDetails,
    GetAccountOwnerDetails0,
    GetAchDetails,
    GetAvailableBalanceLive,
    GetLatestCachedBalance,
    GetLoanPaymentDetails,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: PaymentsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = PaymentsApiRaw(api_client)
