# coding: utf-8

"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.16.0
    Contact: apisupport@mastercard.com
    Created by: https://developer.mastercard.com/open-banking-us/documentation/support/
"""

from mastercard_python_sdk.paths.decisioning_v1_consumers_consumer_id_reports.get import ByConsumerId
from mastercard_python_sdk.paths.decisioning_v1_customers_customer_id_reports.get import ByCustomerId
from mastercard_python_sdk.paths.decisioning_v3_consumers_consumer_id_reports_report_id.get import GetByConsumerAndId
from mastercard_python_sdk.paths.decisioning_v3_customers_customer_id_reports_report_id.get import GetStatus
from mastercard_python_sdk.apis.tags.reports_api_raw import ReportsApiRaw


class ReportsApi(
    ByConsumerId,
    ByCustomerId,
    GetByConsumerAndId,
    GetStatus,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ReportsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ReportsApiRaw(api_client)
