# coding: utf-8

"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.16.0
    Contact: apisupport@mastercard.com
    Created by: https://developer.mastercard.com/open-banking-us/documentation/support/
"""

from mastercard_python_sdk.paths.decisioning_v2_customers_customer_id_voa.post import CustomerVoaReport
from mastercard_python_sdk.paths.decisioning_v2_customers_customer_id_voa_history.post import GenerateVoaWithIncomeReport
from mastercard_python_sdk.paths.decisioning_v2_customers_customer_id_asset_summary.post import GetAssetSummary
from mastercard_python_sdk.paths.decisioning_v2_customers_customer_id_pre_qual_voa.post import GetCheckingSavingsInvestmentAccounts
from mastercard_python_sdk.apis.tags.verify_assets_api_raw import VerifyAssetsApiRaw


class VerifyAssetsApi(
    CustomerVoaReport,
    GenerateVoaWithIncomeReport,
    GetAssetSummary,
    GetCheckingSavingsInvestmentAccounts,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: VerifyAssetsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = VerifyAssetsApiRaw(api_client)
