# coding: utf-8

"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.16.0
    Contact: apisupport@mastercard.com
    Created by: https://developer.mastercard.com/open-banking-us/documentation/support/
"""

from mastercard_python_sdk.paths.decisioning_v2_customers_customer_id_voa.post import CustomerVoaReportRaw
from mastercard_python_sdk.paths.decisioning_v2_customers_customer_id_voa_history.post import GenerateVoaWithIncomeReportRaw
from mastercard_python_sdk.paths.decisioning_v2_customers_customer_id_asset_summary.post import GetAssetSummaryRaw
from mastercard_python_sdk.paths.decisioning_v2_customers_customer_id_pre_qual_voa.post import GetCheckingSavingsInvestmentAccountsRaw


class VerifyAssetsApiRaw(
    CustomerVoaReportRaw,
    GenerateVoaWithIncomeReportRaw,
    GetAssetSummaryRaw,
    GetCheckingSavingsInvestmentAccountsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
