# coding: utf-8

"""
    Open Banking

    OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.16.0
    Contact: apisupport@mastercard.com
    Created by: https://developer.mastercard.com/open-banking-us/documentation/support/
"""

from mastercard_python_sdk.paths.decisioning_v2_customers_customer_id_voi.post import CreateVoiReportRaw
from mastercard_python_sdk.paths.decisioning_v2_customers_customer_id_pay_statement.post import GeneratePayStatementReportRaw
from mastercard_python_sdk.paths.decisioning_v2_customers_customer_id_voe_payroll.post import GenerateVoePayrollReportRaw
from mastercard_python_sdk.paths.decisioning_v2_customers_customer_id_voe_transactions.post import GenerateVoeTransactionsReportRaw
from mastercard_python_sdk.paths.decisioning_v2_customers_customer_id_voie_tx_verify_with_statement.post import GenerateVoiePaystubReportRaw
from mastercard_python_sdk.paths.decisioning_v2_customers_customer_id_voie_tx_verify_with_interview.post import GenerateVoiePaystubWithTxVerifyReportRaw
from mastercard_python_sdk.paths.decisioning_v2_customers_customer_id_voie_payroll.post import RefreshVoiePayrollReportRaw


class VerifyIncomeAndEmploymentApiRaw(
    CreateVoiReportRaw,
    GeneratePayStatementReportRaw,
    GenerateVoePayrollReportRaw,
    GenerateVoeTransactionsReportRaw,
    GenerateVoiePaystubReportRaw,
    GenerateVoiePaystubWithTxVerifyReportRaw,
    RefreshVoiePayrollReportRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
